services:
  dbservice:
    image: mysql
    
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=tradingValley_userdb
      - MYSQL_USER=localUser
      - MYSQL_PASSWORD=password
  
  python-app:
    build: ./
    restart: always
    command: python3 ./app.py;
    depends_on:
      - dbservice
    ports:
      - 5001:5000


  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
  #     - MONGO_INITDB_ROOT_PASSWORD=secret
    # volumes:
    #   - mongo-data:/data/db
  # python:
  #   image: python
  #   # restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
  #   build: ../
  #   command: python3 app.py
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
# volumes:
#   mongo-data:
#     driver: local

# docker run -d \
# -p 3306:3306 \
# -e MYSQL_ROOT_PASSWORD=my-secret-pw \
# -e MYSQL_DATABASE=tradingValley_userdb \
# -e MYSQL_USER=localUser \
# -e MYSQL_PASSWORD=password \
# --name mysqlContainer \
# --network python-app-to-mysql \
#  mysql
