services:
  dbservice:
    build: ./mysql_init
    # image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=tradingValley_userdb
      - MYSQL_USER=localUser
      - MYSQL_PASSWORD=password
    container_name: mysql_container
    volumes:
      - dbservice-db:/var/lib/mysql
  
  python-app:
    build: ./
    restart: always
    command: python3 ./app.py;
    depends_on:
      - dbservice
    ports:
      - 5001:5000

volumes:
  dbservice-db:
    driver: local

